version: "3.3"

services:
  martialarts-tracker-app:
    image: golang:1.9
    volumes:
      - .:/go/src/github.com/DanShu93/martialarts-tracker
    command: go run /go/src/github.com/DanShu93/martialarts-tracker/service.go
    ports:
      - 8888:80
