version: "3.3"

services:
  api:
    image: golang:1.10
    working_dir: /go/src/github.com/DanShu93/martialarts-tracker
    volumes:
      - ./../../../:/go/src/
    command: bash -c "cd /go/src/github.com/DanShu93/martialarts-tracker && go get ./... && go run /go/src/github.com/DanShu93/martialarts-tracker/cmd/server/server.go"
    ports:
      - 8888:80
  db:
    image: mongo:3.6
    volumes:
      - ./data/:/data/db/
    ports:
      - 27017:27017
networks:
  default:
    external:
      name: martialarts-tracker
